blank_issues_enabled: true
contact_links:
  - name: Report a bug with aioschluter
    url: https://github.com/ingos11/aioschluter/issues
    about: Please report issues with aioschluter here.
  - name: I have a question or need support
    url: https://www.home-assistant.io/help
    about: We use GitHub for tracking bugs, check the Home Assistant website for resources on getting help.
